spring:
  rabbitmq:
    one:
      host: 101.132.159.50
      port: 5672
      username: GCC
      password: 1234
      virtual-host: /
    two:
      host: 101.132.159.50
      port: 5672
      username: GCC
      password: 1234
      virtual-host: /